src/azure-account.ts

If the user presses the "Close" button when they get the prompt to copy/paste the device login code, return a rejected promise so that the login process stops.

Handle close button

---

package-lock.json
package.json
src/codeFlowLogin.ts
src/typings/vscode.proposed.d.ts
tsconfig.json

Registers a URI handler and uses the `createAppUri` API to complete auth instead of spinning up a local server.
I wasn't able to test these changes end to end, as the allowed redirect urls need to be updated for the oauth app we're using. For local selfhosting in the web, the redirect will be `http://localhost:9888`
For VSO, the endpoints are
```
https://online.visualstudio.com
https://online-ppe.core.vsengsaas.visualstudio.com
https://online.dev.core.vsengsaas.visualstudio.com
```

Adopt URI handler based auth flow

---

package-lock.json
package.json
src/azure-account.ts
src/cloudConsole.ts
src/nps.ts
src/telemetry.ts

Adopt vscode error telemetry 0.1.15 and ensure we declare the `message` property that's classified as `CallStackOrException` as a property to be removed when needed.
I also increased the version of the extension.

sanitize events from error properties

---

ThirdPartyNotice.txt
package-lock.json
package.json
sample/src/extension.ts
src/azure-account.api.d.ts
src/azure-account.ts
src/cloudConsole.ts
src/cloudConsoleLauncher.ts
src/codeFlowLogin.ts
src/tenantDetailsClient.ts
webpack.config.js

https://github.com/microsoft/vscode-azure-account/issues/140
Migrate to using the new Azure SDK packages internally, but continue to expose the old credentials object in the API for backcompatability. Introduces a new "credentialsV2" property corresponding to the new credentials object

Migrate to new Azure SDK packages

---

src/azure-account.ts

Hey @RMacfarlane, this PR add another inputbox for tenant Id when users are trying to login to Azure Custom Cloud without setting parameters in usersetting.json. Then users don't need to set tenant Id separately in user setting, we believe it would improve user's using experience.

Add tenant intput box to improve user experience

---

src/login/AuthProviderBase.ts
src/login/adal/AdalAuthProvider.ts
src/login/adal/login.ts
src/login/msal/MsalAuthProvider.ts

The device code authentication flow isn't supported for Microsoft employee accounts: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3951#issuecomment-915659897. But it works in cases where the "require managed device" grant control is disabled.
There was some confusion earlier when I thought I got this working for Microsoft employee accounts. I was using the client ID (configured with preauthorization) from the [device code sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/device-code) along with a pre-production authority (again, from the sample code). And under those conditions it works.

Add 'Sign In with Device Code' for MSAL

---

package-lock.json
package.json
src/extension.ts
src/extensionVariables.ts

Per offline discussion with @fiveisprime, we want to do a small release for Account that includes the experimentation service. This will let us run an A/A test before we do the for-real A/B test with MSAL (once that functionality is released). I'd like to do some internal testing on this today and get it out the door tomorrow since it's a small change and because CTI is OOF rn.

Add UI package and experimentation service for patch release

---

CHANGELOG.md
ThirdPartyNotice.txt
package-lock.json
package.json

Since CI/CD isn't set up this far back in the commit history, I grabbed the third party notice for the main branch. It includes `vscode-azureextensionui` (the only package added for this release) but it also includes a notice for `@azure/msal-node` which isn't included as a dependency here. Is that alright?

Prep for 0.9.9

---

package-lock.json
package.json
package.nls.json
src/cloudConsole/CloudShellInternal.ts
src/cloudConsole/cloudConsole.ts
src/extension.ts
src/login/AzureAccountExtensionApi.ts

Fixes https://github.com/microsoft/vscode-azure-account/issues/274
In the extension API we expose a `Terminal` object which is what drove the cloud shell feature before the new `TerminalProfile` was added. This change maintains backwards compatibility by creating a `Terminal` if the entry point is the API and `TerminalProfile` if the entry point it the terminal profile provider (the 'terminal' pane in VS Code).
The difference between `Terminal` and `TerminalProfile` is that `Terminal` exposes all the intimate details about a terminal such as the ability to send text to it while `TerminalProfile` just defines how a terminal will be launched.

Adopt VS Code's terminal profile API for cloud shell

---

package-lock.json
package.json
src/azure-account.api.d.ts
src/azure-account.legacy.api.d.ts
src/login/AuthProviderBase.ts
src/login/msal/MsalAuthProvider.ts
src/login/msal/PublicClientCredential.ts

Fixes https://github.com/microsoft/vscode-azure-account/issues/317
As mentioned in the above issue, `TokenCredentialsBase` is part of the deprecated [@azure/ms-rest-nodeauth](https://github.com/Azure/azure-sdk-for-node) package so it makes sense to switch to the latest & greatest `TokenCredential` from [@azure/core-auth](https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/core/core-auth). This change wasn't too intrusive - the biggest things to note are:
1. I needed to update a few dependencies so that the right credential type is accepted.
2. Since `AzureIdentityCredentialAdapter` is no longer required, I moved where we insert the scope required by the Functions & App Service APIs to PublicClientCredential.ts.

Switch from `TokenCredentialsBase` to `TokenCredential`

---

src/cloudConsole.ts

See [this comment](https://github.com/microsoft/vscode/issues/136987#issuecomment-966914578) for more context on why this change is needed. The `--ms-enable-electron-run-as-node` flag isn't required on Windows and including it throws an error. So I only add the flag for Mac & Linux.
Fixes https://github.com/microsoft/vscode-azure-account/issues/356

Pass in `--ms-enable-electron-run-as-node` flag when creating the cloud shell process

---

src/login/AzureLoginHelper.ts

Fixes https://github.com/microsoft/vscode-azure-account/issues/364
In `sendLoginTelemetry`, we await `api.waitForSubscriptions` which won't resolve until this line executes:
https://github.com/microsoft/vscode-azure-account/blob/e3bd4d4d94b773fb9b36dbe9a1361c8d9feca653/src/login/AzureLoginHelper.ts#L169
The problem is: the `api.waitForSubscriptions` Promise would never resolve because `sendLoginTelemetry` is called before `updateLoginStatus`. So not awaiting the calls to `sendLoginTelemetry` fixes the problem.

Don't wait when sending login telemetry

---

src/cloudConsole/cloudConsole.ts

Fixes https://github.com/microsoft/vscode-azure-account/issues/365
I opted to add a log to the shell instead of throwing a "traditional" error because the TerminalProfile throws additional errors when a profile isn't provided (which is what happens when we throw an error from `createCloudConsole`)

Throw a pretty error when attempting to authenticate Cloud Shell with MSAL

---

src/constants.ts
src/login/msal/MsalAuthProvider.ts
src/login/msal/PublicClientCredential.ts

The original default scope 'user.read' has always been more of a placeholder than something that's actually needed (it governs read access to Microsoft Graph resources). It started causing problems[^1] when I was implementing MSAL support for Cloud Shell and I figured it's better to remove it sooner rather than later.
[^1]: The Cloud Shell API threw an error related to the audience for any tokens acquired with that 'user.read' scope. And Cloud Shell requires the 'https://management.core.windows.net' audience anyway so this change makes sense.

Update default MSAL scope

---

package.json

Fixes https://github.com/microsoft/vscode-azure-account/issues/372
Adding the bugs URL resolves the problem outlined in https://github.com/microsoft/vscode-azure-account/issues/372#issuecomment-981977278 because the incorrect GitHub issue URL is only created if `bugs` doesn't exist in package.json.
I also removed the `enableProposedApi` property which has been replaced (we aren't using any API proposals at the moment anyway):

Add bugs URL to package.json, update homepage URL

---

package.json
package.nls.json
src/extension.ts

Fixes https://github.com/microsoft/vscode-azure-account/issues/371
I added this command under the category "Azure Account" instead of "Azure" which is what we normally do for this extension. The `Azure: Report Issue...` command already exists and it would look gross if we added another command with the same name:

Add `Azure Account: Report Issue...` command

---

package.json
src/cloudConsole/cloudConsole.ts
src/extension.ts
src/extensionVariables.ts
src/login/AzureLoginHelper.ts
src/login/getAuthLibrary.ts
src/utils/settingUtils.ts

The user's `azure.authLibrary` setting takes precedence over the auth library the experimentation framework tells us to use. Also I added telemetry for the auth library setting so we can filter out users from the A/B test reports who manually set their auth library (I believe that's all that is required in the extension to do that filtering)

Set authentication library based on user setting and exp framework

---

src/extension.ts

When I was investigating https://github.com/microsoft/vscode-azure-account/issues/380 I noticed we weren't pushing these disposables to `context.subscriptions`.

Push `registerTerminalProfileProvider` calls to subscriptions

---

.vscode/settings.json
package.json
package.nls.json
src/extension.ts
src/login/AzureLoginHelper.ts
src/login/commands/selectTenant.ts
src/login/filters.ts
src/login/subscriptionTypes.ts
src/login/updateFilters.ts
src/login/updateSubscriptions.ts
src/utils/settingUtils.ts

Fixes https://github.com/microsoft/vscode-azure-account/issues/101
I also updated the [troubleshooting wiki page](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting) to recommend this command first when troubleshooting tenant problems.
One potential issue here is if a user enters a custom tenant that is wrong then attempts to sign in, they won't be able to use the "Select Tenant" command to update the tenant. This is because we require the user to be signed in when this command is run to dynamically get a list of available tenants.

Add 'Select Tenant' command

---

src/extension.ts
src/login/AuthProviderBase.ts
src/login/AzureLoginHelper.ts
src/login/commands/selectTenant.ts
src/login/filters.ts
src/login/subscriptionTypes.ts
src/login/updateFilters.ts
src/login/updateSubscriptions.ts

I didn't properly understand the relationship between tenants & subscriptions when I first introduced the "Select Tenant" command in https://github.com/microsoft/vscode-azure-account/pull/395 so I've fixed it here. Shoutout to @nturinski and @alexweininger for helping me get a better handle on how these things are related.
A few things to note about this change:
* We can only list subscriptions associated with the tenant the user signed in with. We have access to list all tenants available to a particular user though. So in the cache, the list of all available tenants is now stored at the same level in the object as the subscriptions list.
* We no longer require the user to be signed in to run the "Select Tenant" command. This requirement originally created a "chicken & the egg" problem. …

Rework 'Select Tenant' command

---

src/login/AzureLoginHelper.ts
src/login/TenantIdDescription.ts
src/login/commands/selectTenant.ts
src/login/subscriptionTypes.ts
src/login/updateSubscriptions.ts

Fixes https://github.com/microsoft/vscode-azure-account/issues/398
Here's how the new "Select Tenant" command looks. The display name for each tenant is now the "description" for the quick pick items.

Show tenant `displayName` in tenants quick pick

---

src/cloudConsole/cloudConsole.ts

Fixes https://github.com/microsoft/vscode-azure-account/issues/391
This issue was caused by https://github.com/microsoft/vscode-azure-account/pull/357 which was the fix for https://github.com/microsoft/vscode/issues/136987. Turns out that Linux doesn't like the `ms-enable-electron-run-as-node` flag along with Windows. And both Codespaces and WSL are Linux products so that explains https://github.com/microsoft/vscode-azure-account/issues/391.

Only add `ms-enable-electron-run-as-node` flag to cloud shell process for Mac platform

---

.azure-pipelines/main.yml

This fixes the mac pipeline which had been failing for a bit because the hard coded image is longer available.
> An image label with the label macOS-10.14 does not exist. ([source](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=42546&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7))

Switch to latest VM image for mac builds

---

package.json
src/extension.ts
src/extensionVariables.ts
src/login/getAuthLibrary.ts

This leans on VS Code's support for [experimental settings](https://github.com/microsoft/vscode/issues/134684). I removed the old `azure-account.isMsal` treatment variable. We'll have to reconfigure our A/B test to use the `azure.authenticationLibrary` setting.

Add 'experimental' tag to auth library setting for easier A/B testing

---

.azure-pipelines/compliance/CredScanSuppressions.json

I searched for the culprit for this credscan hit and was unable to find it. I argue that it's OK to suppress for the reasons listed in `_justification`.

Suppress credscan for suspected password found in extension.bundle.js.map

---

src/login/msal/PublicClientCredential.ts

@nturinski suggested adding this and I think it's helpful especially since we don't publicize our support for `AzExtServiceClientCredentials` in the API.

Add clarifying comment to `PublicClientCredential`

---

src/cloudConsole/cloudConsole.ts

Fixes https://github.com/microsoft/vscode-azure-account/issues/391
Codespaces running in web (Linux OS) *does not* need the flag while normal Linux running on desktop *does* need the flag. 
This gets messy because Codespaces running locally *does not* need the flag but as far as I can tell there isn't a way to know when the extension is being run from local Codespaces. VS Code's `appHost` and `uiKind` both read as `desktop` in this situation. 
So I'm making the conscious decision to not support cloud shell on local Codespaces because it doesn't seem worth the investigation time. With this change, we'll support cloud shell on Windows, Mac, Linux, and Codespaces Web.
For context, here's the flag requirements I gathered from my testing:
| Platform | Flag required? |
|-|:-:|
|Windows|❌| …

Update when `ms-enable-electron-run-as-node` flag is added to cloud shell process

---

package.json
src/extension.ts
src/login/AuthLibraryCache.ts
src/login/AzureLoginHelper.ts

Fixes https://github.com/microsoft/vscode-azure-account/issues/433
Thanks @bwateratmsft for the investigation you did on this one. 
This change adds caching for the last seen auth library setting. At startup, it compares that value to the current auth library and if they're different, the extension prompts the user to sign out & reload the window.
I also added the machine-overridable scope to the auth library setting as suggested in https://github.com/microsoft/vscode-azure-account/issues/433#issuecomment-1036348207.

Prompt to sign out and reload window if the auth library changed since last session

---

src/login/commands/loginToCloud.ts

The tenant setting was being updated when it should have been updating the cloud setting. This was the culprit for issues like this where an incorrect tenant ID was being used to sign in:

Use the proper setting key when updating cloud setting

---

src/login/AuthProviderBase.ts
src/login/AzureLoginHelper.ts
src/login/adal/AdalAuthProvider.ts
src/login/adal/tokens.ts

When testing https://github.com/microsoft/vscode-azure-account/pull/470 I noticed that switching between sovereign clouds while also changing the tenant using the `Azure: Sign In to Azure Cloud` command resulted in several errors ranging from cache read errors to "invalid grant".
This was happening because [this config watcher]( https://github.com/microsoft/vscode-azure-account/blob/36e0a4727655637eed6dd4ea84503e290f1fe660/src/login/AzureLoginHelper.ts#L74-L79) was activating twice: once for the cloud change and again for the tenant change. This was on top of the initialization function being called upon extension activation. These calls resulted in the cache being in a strange state when `loginSilent` was called and caused the above errors.
To fix this I force a logout before every …

Changes to login and initialization

---

src/login/commands/loginToCloud.ts
src/login/updateSubscriptions.ts
src/utils/settingUtils.ts

* Fix infinite loop in `loadTenants` when there's an error in the server response
* Finish running `Azure: Sign In to Azure Cloud` command even when the tenant ID is set to an empty string
* Get current target when updating setting value. This fixes the "Unable to write to Workspace Settings because no workspace is opened. Please open a workspace first and try again." error while running `Azure: Select Tenant` command

Tenant setting-related changes

---

package.json

Serene brought it to my attention that for a particular version of VS Code, "Azure" wasn't shown as an option for the `azure.cloud` setting:
In package.json, "Azure" (the default setting value) isn't actually included in the enum list:
https://github.com/microsoft/vscode-azure-account/blob/0231ca49f318a62b9ddf9174bd8bebd01b8a17e1/package.json#L143-L149
This led to the strange behavior in VS Code where "Azure" was sometimes shown in the list of potential Azure cloud setting values. This seems to have been done by mistake so I changed the default to "AzureCloud". 
I'm confident that this is an OK change after seeing the following function which is used to migrate from the old "Azure" cloud name to the new one ("AzureCloud"). So it turns out "Azure" was never actually being stored as a …

Change `azure.cloud` default to "AzureCloud" instead of "Azure"

---

src/cloudConsole/ipc.ts

The following error was being thrown on cloud shell startup for ADAL & MSAL regardless of Azure cloud type.
It was happening because the following line I added pulls the whole UI package into the `cloudConsoleLauncher` entry point (configured [here](https://github.com/microsoft/vscode-azure-account/blob/0f33c01a1f8d0feb6469b1e700ebd73122964255/webpack.config.js#L20)). The cloud console launcher runs out of process and so it can't access the vscode API.
https://github.com/microsoft/vscode-azure-account/blob/0f33c01a1f8d0feb6469b1e700ebd73122964255/src/cloudConsole/ipc.ts#L42
Removing that single reference to `parseError` removes >20k likes of code from cloudConsoleLauncher.js and fixes this problem 😄

Don't use `parseError` in ipc.ts

---

src/login/commands/selectTenant.ts

Since a logout is forced before logging in (this is the case after the work in https://github.com/microsoft/vscode-azure-account/pull/472), this prompt was no longer accurate.

Only ask user to 'sign in again' after tenant change

---

src/cloudConsole/cloudConsole.ts
src/logAttemptingToReachUrlMessage.ts
src/login/AuthProviderBase.ts
src/login/waitUntilOnline.ts

Fixes https://github.com/microsoft/vscode-azure-account/issues/419
This PR specifically address this bullet from the above issue:
> Know which URLs the extension is attempting to hit so the user can configure their proxy accordingly. This could be done in the error notifications or in the logs.
I don't want to add a mechanism to turn off the "is this machine online" check for reasons listed in that issue.
I did my best to catch all the URLs and avoid too many duplicate URLs 🕵️‍♂️
Here's how the output channel looks during the sign in process:

Log all URLs that the extension tries to reach

---

package-lock.json

Fixes [CVE-2022-24785](https://github.com/moment/moment/security/advisories/GHSA-8hfj-j24r-96c4)

Update moment to 2.29.2 to fix CVE-2022-24785

---

src/constants.ts
src/login/AuthProviderBase.ts
src/login/exchangeCodeForToken.ts
src/login/getCallbackUrl.ts
src/login/server.ts

The VS Code team switched to using `https://vscode.dev/redirect` and will soon be deprecating the old redirect server (`https://vscode-redirect.azurewebsites.net/`). 
The old redirect server required a very specific `state` to perform redirects. If the state format wasn't matched, the server would return an error code.
The new redirect server's `state` is simply the URL we wish to redirect to. I still include the nonce in the redirect URL so we can check it upon receiving the auth code.

Use new redirect server

---

src/login/AzureLoginHelper.ts
src/login/updateSubscriptions.ts

The DevDiv Analytics and Growth Team now relies on the `subscriptions` property of the `updateSubscriptionsAndTenants` event.
I'm removing the subscriptions property from `AzureLoginHelper` due to difficult to diagnose timing issues. It's much easier to put the property on `updateSubscriptionsAndTenants` and that satisfies the needs of the partner team.
Apologies for the random whitespace changes. I had my auto-formatter turned off.

Add `updateSubscriptionsAndTenants/subscriptions` telemetry event

---

package-lock.json
package.json

2.6.2 of `ms-rest-azure` has a fixed 2.6.4 version of `async`.

Update `ms-rest-azure` to fix CG alert

---

src/login/checkSettingsOnStartup.ts

The first time the Account extension runs on an installation of VS Code, the settings cache we keep is undefined. The current logic sees that undefined is different from the current settings values (defaults) and we prompt the user to sign in a reload (before they have even signed in).
Edit: found this bug when trying to fix the tests

Don't prompt to sign out and reload on first run

---

src/cloudConsole/cloudConsole.ts

Fixes #682, #601 
This fixes connecting to Cloud Shell while connected to _something_ (WSL, CodeSpaces, Dev Container, etc.) from VS Code desktop.
This flag should only be used when executing Node from an Electron process. However, many scenarios of VS Code are not Electron processes anymore, and are just plain Node processes.
We had covered most cases by checking if UiKind === Desktop, however cases like connecting to Codespaces from VS Code Desktop were not covered.
To fix this, we can check if the current process is Electron by checking if `process.versions['electron']` is defined.
Related PRs:
https://github.com/microsoft/vscode-azure-account/pull/432 
https://github.com/microsoft/vscode-azure-account/pull/357
https://github.com/microsoft/vscode/issues/136987

Only add electron run as node when in electron

---

package-lock.json
package.json
src/cloudConsole/cloudConsole.ts
src/cloudConsole/cloudConsoleLauncher.ts
src/extension.ts
src/extensionVariables.ts
src/login/AuthProviderBase.ts
src/login/AzureAccountLoginHelper.ts
src/login/adal/AdalAuthProvider.ts
src/login/adal/tokens.ts
src/login/environments.ts
src/login/msal/MsalAuthProvider.ts
src/login/updateSubscriptions.ts
src/utils/logErrorMessage.ts
src/utils/logging/HttpLogger.ts
src/utils/logging/axios/AxiosNormalizer.ts
src/utils/logging/msRest/LogRequestPolicy.ts
src/utils/logging/msRest/MsRestNormalizer.ts
src/utils/logging/nodeFetch/NodeFetchNormalizer.ts
src/utils/logging/nodeFetch/nodeFetch.ts
src/utils/logging/request/RequestNormalizer.ts
src/utils/logging/stringifyHttp.ts

MSAL and ADAL both have logging channels we can hook into, so I did that. For Http logging, there are 4+ http clients used in Azure Account, and I added normalizers for each of them. Until we add a feature that auto attaches logs to GH issues, we don't need to worry about masking. Although I am logging simpler HTTP messages when the log level is info, and logging more info when the log level is debug or trace.
I did some fancier things with the logs with the idea that we'll be able to use these in other extensions later on. Once we get around to adding logging to the other extension I'll move some of common classes to the utils package. Maybe we make a new package for logging? `@microsoft/vscode-azext-logging` 😄

Add detailed logging 

---

src/cloudConsole/cloudConsole.ts
src/cloudConsole/cloudConsoleLauncher.ts

Adding logging broke the cloud console launcher. `cloudConsoleLauncher.ts` is launched as a new process. Because of this, you can't try and import variables and whatnot from the extension process. I removed the logging from the file and it works again.
Users have been reporting this in https://github.com/microsoft/vscode-azure-account/issues/682
Fixes https://github.com/microsoft/vscode-azure-account/issues/808

Fix cloud console

---

src/utils/logging/nodeFetch/nodeFetch.ts

The underlying data is created using stream, which means you can only call `json` and `text` once, unless you clone it. We need to clone it here in case code outside the logger calls `json` or `text`.

Clone response in logger

---

src/cloudConsole/cloudConsole.ts

A new feature for cloud shell is ephemeral sessions. These sessions no longer require users to configure a storage account and file share to attach cloud shell to. This change makes our feature work with cloud shell if the user has set it up to use ephemeral sessions on the portal.

Support ephemeral cloud shell sessions

---

.vscode/settings.json
package.json
package.nls.json
src/extension.ts

Related to https://github.com/microsoft/vscode-azureresourcegroups/pull/848
The idea is to make RGs an extension dependency so that users don't notice any UI changes. However, the entry point for cloud shell will now be contributed by RGs instead of Azure Account. This will be a great way to easily transition users to RGs.
Keeping the cloud shell code around because some extensions still rely on the API, which has yet to be migrated to RGs. One of which is https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azureterraform
They can rely on AA until we figure out a solution

Depend on Azure Resources extension for Cloud Shell feature
