microsoft/vscode-azure-account

src/extension.ts
show the subscription filter when the user clicks on the status bar...
=> show subscription filter from status bar

src/azure-account.ts
If the user click `copy & open` but doing nothing else. Then the extension will keep waiting for the response. So I added a timeout here.
The 3 minutes is just estimated by myself.
=> add timeout in promise race

package-lock.json, package.json
The current version of `vscode` has dependencies that have known security vulnerabilities
=> Update vscode dependency

src/azure-account.ts
https://github.com/Microsoft/vscode-azure-account/issues/103
=> fix Azure China sign in issue

package-lock.json, package.json, webpack.config.js
This appears to keep everything the same except that AbortSignal is preserved as a class name. The VISX even shrunk a bit (not sure how, maybe some compression effect). I can sign in with this VISX.
=> Preserve AbortSignal class name

src/azure-account.ts, src/checkIsOnline.ts, src/constants.ts, src/deviceLogin.ts, src/environments.ts, src/extension.ts, src/filters.ts, src/tokens.ts, src/utils/arrayUtils.ts, src/utils/openUri.ts, src/utils/timeUtils.ts
I'll rename these files as needed in the next PR
=> Engineering changes for login-related files and utils

package-lock.json, package.json
Fixes https://github.com/microsoft/vscode-azure-account/issues/291
CVE-2021-28458 was mitigated in [v3.0.8](https://github.com/Azure/ms-rest-nodeauth/blob/master/Changelog.md#308---20210323)
=> Bump @azure/ms-rest-nodeauth

package.json
Per an ask from the VS Code team
=> Add 'application' scope to a few settings

src/extension.ts, src/extensionVariables.ts
Fixes https://github.com/microsoft/vscode-azure-account/issues/324
=> Add experimentation service

src/cloudConsole/cloudConsole.ts, src/extension.ts, src/login/AzureAccountExtensionApi.ts, src/login/AzureAccountExtensionLegacyApi.ts, src/login/server.ts, src/utils/promiseUtils.ts
These are purely engineering changes. And I added a test case for cloud shell to the onenote which passes for these changes.
=> Add types & update variable names in cloudConsole.ts

src/login/AzureLoginHelper.ts
Fixes https://github.com/microsoft/vscode-azure-account/issues/309
There were several problems with switching to a different auth library and reloading the VS Code window without signing out. The unhandled cache read error `SyntaxError: Unexpected token A in JSON at position 2` from the linked issue is one of them. Another problem is that you could never actually sign out of the old auth library you had selected since we didn't keep that instance of the `AdalAuthProvider` or `MsalAuthProvider` around.
To avoid these problems, this change ensures that we always clear sessions for both ADAL and MSAL. When that cache read error is handled as the extension initializes, the old auth library's session will be cleared so users can sign in with the selected library.
=> Always clear cache for all auth libraries

sample/.vscode/tasks.json, sample/package-lock.json, sample/package.json, sample/src/extension.ts
A few housekeeping changes here:
* This sample code was relying on dependencies not found in its package.json so I added those.
* Parts of tasks.json were automatically updated by VS Code when I debugged.
* The script we had for post-install (`./node_modules/vscode/bin/install`) doesn't exist after switching to the "@types/vscode" package so I removed it.
* `AzureAccount` ➡️  `AzureAccountExtensionApi`
=> Update extension sample

CHANGELOG.md, package-lock.json, package.json, src/cloudConsole/cloudConsole.ts
Here's the release branch diff for reference: https://github.com/microsoft/vscode-azure-account/compare/rel/0.9.10...rel/0.9.11
=> Bump version and implement changes from 0.9.11 on main

src/extension.ts
I should have added this in https://github.com/microsoft/vscode-azure-account/pull/353 😯
=> Add experimentation service to main branch

src/login/AzureLoginHelper.ts
Fixes https://github.com/microsoft/vscode-azure-account/issues/354
=> Provide a link to troubleshooting page when no subscriptions are found

src/login/AzureLoginHelper.ts
From https://github.com/microsoft/vscode-azure-account/pull/362#discussion_r758711087
=> Add telemetry to `showNoSubscriptionsFoundNotification`

package-lock.json, package.json, src/login/msal/PublicClientCredential.ts
Fixes https://github.com/microsoft/vscode-azure-account/issues/386
=> Implement `signRequest` in `PublicClientCredential`

.github/ISSUE_TEMPLATE/bug-report.md
Fixes https://github.com/microsoft/vscode-azure-account/issues/366
=> Add 'bug report' issue template

sample/package-lock.json
=> Update node-fetch to 2.6.7 in sample extension

.azure-pipelines/common/build.yml, package-lock.json, package.json, src/login/server.ts
Fixes https://github.com/microsoft/vscode-azure-account/issues/416
=> Bump VS Code engine and vsce

src/constants.ts, src/login/msal/MsalAuthProvider.ts, src/login/msal/PublicClientCredential.ts, src/login/msal/getAzureCloudInstance.ts, src/login/msal/getDefaultMsalScopes.ts
Fixes https://github.com/microsoft/vscode-azure-account/issues/441
=> Include cloud instance and tenant in MSAL auth calls

src/extension.ts, src/login/AzureLoginHelper.ts, src/login/commands/loginToCloud.ts, src/login/commands/selectSubscriptions.ts, src/login/commands/selectTenant.ts
We need this change in order to add a debounce when users click the "Sign In..." tree item.
=> Use `registerCommand` from `vscode-azext-utils`

src/cloudConsole/ipc.ts, src/constants.ts, src/login/AuthProviderBase.ts, src/login/AzureLoginHelper.ts, src/login/adal/AdalAuthProvider.ts, src/login/commands/loginToCloud.ts, src/login/msal/MsalAuthProvider.ts, src/login/server.ts, src/utils/timeUtils.ts
Fixes https://github.com/microsoft/vscode-azure-account/issues/468
=> Show cancellable, long running notification when signing in

src/login/commands/loginToCloud.ts
Fixes https://github.com/microsoft/vscode-azure-account/issues/490
=> Update tenant ID placeholder verbiage

src/login/commands/selectTenant.ts
Fixes https://github.com/microsoft/vscode-azure-account/issues/500
=> Remove 'workspace' from select tenant prompt

sample/package-lock.json, sample/package.json, sample/src/extension.ts
* Use `getApi` from `@microsoft/vscode-azext-utils` to use the latest extension API instead of the legacy API
* Fix ES Lint errors
* Update a few packages to match the main extension package.json
Fixes https://github.com/microsoft/vscode-azure-account/issues/510
=> Update sample extension

src/login/AzureLoginHelper.ts, src/login/commands/selectTenant.ts
Fixes https://github.com/microsoft/vscode-azure-account/issues/243
There are a few cases when the logout function is called where we don't want this prompt shown so I made them forced logouts.
=> Show prompt to clear tenant when signing out

src/extension.ts
Fixes https://github.com/microsoft/vscode-azure-account/issues/284
=> Add id and name to status bar entry

package-lock.json, package.json, src/cloudConsole/cloudConsole.ts
Fixes https://github.com/microsoft/vscode-azure-account/issues/380
Support for this flag was introduced in VS Code v1.65.0 so I bumped types/vscode & the engine. It's a pretty aggressive version bump on our end though so if this change doesn't seem worth it I'm fine waiting on it.
=> Add `isTransient` flag to cloud shell terminal

src/extension.ts, src/login/commands/loginToCloud.ts
Thanks @nturinski for the suggestion. I'm surprised we didn't already have this!
=> Add some telemetry for the cloud setting

.vscode/extensions.json, docs/DESIGN.md
Starts a design document for the extension, mostly to help wrap my head around the existing authentication flow.
=> Start extension design document

package.json, package.nls.json, src/cloudConsole/cloudConsole.ts, src/extension.ts
Azure account extension will be activated in "Restricted Mode" with limited support.
=> Add Support for Workspace Trust

package-lock.json, package.json, src/cloudConsole/cloudConsoleLauncher.ts, tsconfig.json
Potentially fixes the not-getting-any-telemetry-at-all issue. I've tested this without a proxy and it works fine. I have not yet tested with a proxy.
=> Update `http-proxy-agent` and `https-proxy-agent`

src/extension.ts, src/nps.ts
=> Don't await nps survey

CHANGELOG.md, NOTICE.txt, package-lock.json, package.json
https://github.com/microsoft/azcode-internal/issues/28
=> 0.11.4 release prep: Bump version, update changelog, and update notice

package.json, package.nls.json, src/commands/manageAccount.ts, src/extension.ts
Fixes #739 
Clicking the status bar item shown here now opens a menu where users can select to sign out or select subscriptions.
=> Add manage account command

src/cloudConsole/cloudConsole.ts
Closes #849 
AAD Graph was being used by cloud shell in two ways:
1. If a user had subscriptions from multiple tenants, we let the user select which tenant to launch the cloud shell in. A Graph API endpoint for listing user tenants was used to populate the quick pick.
I replaced this with a call to the new List Tenants ARM endpoint. https://learn.microsoft.com/en-us/rest/api/resources/tenants/list
2. We fetched an AAD Graph token and passed it to Cloud Shell upon initialization.
I just stopped fetching and passing this token. My reasoning is that any features relying on this token will also break once AAD Graph is gone. So there's no reason to keep passing this token.
=> Remove use of AAD Graph for cloud shell

src/cloudConsole/cloudConsole.ts
=> Set referer header for cloud shell

src/cloudConsole/cloudConsoleLauncher.ts
=> Fix cloud shell resize request

package.nls.json
Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/858
=> Make "Select subscription" command titles match

CHANGELOG.md, README.md, package-lock.json, package.json
Please review the change log since it's longer than usual 😄
=> Bump version and update changelog for 0.12.0 release
